from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///jrdb.db'
db = SQLAlchemy(app)

class BangumiData(db.Model):
    __tablename__ = 'bangumi'
    racekey=db.Column(db.String(80),primary_key=True)
    #親に対して
    kaisaikey=db.Column(db.String(80),db.ForeignKey('kaisai.kaisaikey'))
    #子に対して
    racehorses = db.relationship("RacehorseData",backref=db.backref('bangumi'),lazy='subquery',innerjoin=True)

    #1:1
    returninfo = db.relationship("ReturninfoData",uselist=False, backref=db.backref('bangumi',lazy='joined'))
    ymd=db.Column(db.String(80))
    start_time=db.Column(db.String(80))
    distance=db.Column(db.Integer)
    tdscode=db.Column(db.Integer)
    right_left=db.Column(db.Integer)
    in_out=db.Column(db.Integer)
    shubetsu=db.Column(db.Integer)
    joken=db.Column(db.String(80))
    kigo=db.Column(db.Integer)
    horse_kind_joken = db.Column(db.Integer)
    horse_sex_joken = db.Column(db.Integer)
    inter_race_joken = db.Column(db.Integer)
    juryo=db.Column(db.Integer)
    grade=db.Column(db.Integer)
    race_name=db.Column(db.String(80))
    kai=db.Column(db.String(80))
    num_of_all_horse=db.Column(db.Integer)
    course=db.Column(db.Integer)
    kaisai_kbn=db.Column(db.Integer)
    race_name_short=db.Column(db.String(80))
    race_name_9char=db.Column(db.String(80))
    data_kbn=db.Column(db.Integer)
    money1st=db.Column(db.Integer)
    money2nd=db.Column(db.Integer)
    money3rd=db.Column(db.Integer)
    money4th=db.Column(db.Integer)
    money5th=db.Column(db.Integer)
    sannyu_money1st=db.Column(db.Integer)
    sannyu_money2nd=db.Column(db.Integer)
    sellflg_tansho=db.Column(db.Integer)
    sellflg_fukusho=db.Column(db.Integer)
    sellflg_wakuren=db.Column(db.Integer)
    sellflg_umaren=db.Column(db.Integer)
    sellflg_umatan=db.Column(db.Integer)
    sellflg_wide=db.Column(db.Integer)
    sellflg_sanrenpuku=db.Column(db.Integer)
    sellflg_sanrentan=db.Column(db.Integer)
    yobi=db.Column(db.Integer)
    win5flg=db.Column(db.Integer)

class RacehorseData(db.Model):
    __tablename__ = 'racehorse'
    racehorsekey = db.Column(db.String(80),db.ForeignKey('seiseki.racehorsekey'),primary_key=True)
    #親に対して
    racekey = db.Column(db.String(80),db.ForeignKey('bangumi.racekey'))
    #1:1
    trainanalysis = db.relationship("TrainAnalysisData",uselist=False, backref=db.backref("racehorse",lazy='joined'),innerjoin=True)
    trainoikiri = db.relationship("TrainOikiriData",uselist=False, backref=db.backref("racehorse",lazy='joined'),innerjoin=True)
    horse_base = db.relationship("HorsebaseData",uselist=False,backref=db.backref("racehorse",lazy='joined'),innerjoin=True)
    result = db.relationship("SeisekiData",uselist=False,foreign_keys=[racehorsekey],lazy='joined',innerjoin=False)
    #インデックスに対して
    horseidx = db.relationship("HorseIndex",uselist=False,backref=db.backref("racehorse",lazy='joined'))
    jockeyidx = db.relationship("JockeyIndex",uselist=False,backref=db.backref("racehorse",lazy='joined'))
    traineridx = db.relationship("TrainerIndex",uselist=False,backref=db.backref("racehorse",lazy='joined'))
    hobokusakiidx = db.relationship("HobokusakiIndex",uselist=False,backref=db.backref("racehorse",lazy='joined'))
    bacode = db.Column(db.Integer)
    year = db.Column(db.Integer)
    kai = db.Column(db.Integer)
    day = db.Column(db.Integer)
    race = db.Column(db.Integer)
    num=db.Column(db.Integer)
    blood=db.Column(db.Integer)
    horse=db.Column(db.String(80))
    idm=db.Column(db.Integer)
    jockey_score=db.Column(db.Integer)
    info_score=db.Column(db.Integer)
    yobi1=db.Column(db.String(80))
    yobi2=db.Column(db.String(80))
    yobi3=db.Column(db.String(80))
    sogo_score=db.Column(db.Integer)
    leg_type=db.Column(db.Integer)
    distance_adjust=db.Column(db.Integer)
    up_degree=db.Column(db.Integer)
    routin=db.Column(db.Integer)
    cri_odds=db.Column(db.Integer)
    cri_popular_order=db.Column(db.Integer)
    cri_fukusho_odds=db.Column(db.Integer)
    cri_fukusho_popluar_order=db.Column(db.Integer)
    specific_info_1=db.Column(db.Integer)
    specific_info_2=db.Column(db.Integer)
    specific_info_3=db.Column(db.Integer)
    specific_info_4=db.Column(db.Integer)
    specific_info_5=db.Column(db.Integer)
    sogo_info_1=db.Column(db.Integer)
    sogo_info_2=db.Column(db.Integer)
    sogo_info_3=db.Column(db.Integer)
    sogo_info_4=db.Column(db.Integer)
    sogo_info_5=db.Column(db.Integer)
    pop_score=db.Column(db.Integer)
    train_score=db.Column(db.Integer)
    trainer_score=db.Column(db.Integer)
    train_code=db.Column(db.Integer)
    trainer_hyoka_code=db.Column(db.Integer)
    jockey_rate_rentai=db.Column(db.Integer)
    gekiso_score=db.Column(db.Integer)
    hidume_code=db.Column(db.Integer)
    hidume_shape=db.Column(db.Integer)
    hidume_size=db.Column(db.Integer)
    omotekisei_code=db.Column(db.Integer)
    class_code=db.Column(db.Integer)
    yobi4=db.Column(db.String(80))
    brinkers=db.Column(db.String(80))
    jockey_name=db.Column(db.String(80))
    kinryo=db.Column(db.Integer)
    minarai=db.Column(db.Integer)
    trainer_name=db.Column(db.String(80))
    trainer_shozoku=db.Column(db.String(80))
    zenso_seiseki_key_1=db.Column(db.String(80),db.ForeignKey('seiseki.raceseisekikey'))
    zenso_seiseki_key_2=db.Column(db.String(80),db.ForeignKey('seiseki.raceseisekikey'))
    zenso_seiseki_key_3=db.Column(db.String(80),db.ForeignKey('seiseki.raceseisekikey'))
    zenso_seiseki_key_4=db.Column(db.String(80),db.ForeignKey('seiseki.raceseisekikey'))
    zenso_seiseki_key_5=db.Column(db.String(80),db.ForeignKey('seiseki.raceseisekikey'))
    zenso1 = db.relationship("SeisekiData",uselist=False,foreign_keys=[zenso_seiseki_key_1],lazy='joined',innerjoin = False)
    zenso2 = db.relationship("SeisekiData",uselist=False,foreign_keys=[zenso_seiseki_key_2],lazy='joined',innerjoin = False)
    zenso3 = db.relationship("SeisekiData",uselist=False,foreign_keys=[zenso_seiseki_key_3],lazy='joined',innerjoin = False)
    zenso4 = db.relationship("SeisekiData",uselist=False,foreign_keys=[zenso_seiseki_key_4],lazy='joined',innerjoin = False)
    zenso5 = db.relationship("SeisekiData",uselist=False,foreign_keys=[zenso_seiseki_key_5],lazy='joined',innerjoin = False)
    zenso_racekey_1=db.Column(db.String(80))
    zenso_racekey_2=db.Column(db.String(80))
    zenso_racekey_3=db.Column(db.String(80))
    zenso_racekey_4=db.Column(db.String(80))
    zenso_racekey_5=db.Column(db.String(80))
    waku=db.Column(db.Integer)
    yobi5=db.Column(db.String(80))
    sogo_shirushi=db.Column(db.Integer)
    idm_shiruishi=db.Column(db.Integer)
    info_shirushi=db.Column(db.Integer)
    jockey_shirushi=db.Column(db.Integer)
    trainer_shirushi=db.Column(db.Integer)
    train_shirushi=db.Column(db.Integer)
    gekiso_shirushi=db.Column(db.Integer)
    turf_adjust_code=db.Column(db.Integer)
    dart_adjust_code=db.Column(db.Integer)
    jockey_code=db.Column(db.Integer)
    trainer_code=db.Column(db.Integer)
    yobi6=db.Column(db.String(80))
    kakutoku_money=db.Column(db.Integer)
    shukaku_money=db.Column(db.Integer)
    joken=db.Column(db.Integer)
    ten_score=db.Column(db.Integer)
    pace_score=db.Column(db.Integer)
    up_score=db.Column(db.Integer)
    position_score=db.Column(db.Integer)
    pace_predict=db.Column(db.String(80))
    dochu_order=db.Column(db.Integer)
    dochu_sa=db.Column(db.Integer)
    dochu_in_out=db.Column(db.Integer)
    last_order=db.Column(db.Integer)
    last_sa=db.Column(db.Integer)
    last_in_out=db.Column(db.Integer)
    order=db.Column(db.Integer)
    sa=db.Column(db.Integer)
    in_out=db.Column(db.Integer)
    tenkai=db.Column(db.String(80))
    distance_adjust2=db.Column(db.Integer)
    commit_weight=db.Column(db.Integer)
    commit_weight_increase=db.Column(db.Integer)
    torikeshi=db.Column(db.Integer)
    sex=db.Column(db.Integer)
    owner_name=db.Column(db.String(80))
    banushikai_code=db.Column(db.Integer)
    umakigo_code=db.Column(db.Integer)
    gekiso_order=db.Column(db.Integer)
    ls_score_order=db.Column(db.Integer)
    ten_score_order=db.Column(db.Integer)
    pace_score_order=db.Column(db.Integer)
    up_score_order=db.Column(db.Integer)
    position_score_order=db.Column(db.Integer)
    expect_jokey_win_rate=db.Column(db.Integer)
    expect_jokey_rentai_rate=db.Column(db.Integer)
    yuso=db.Column(db.String(80))
    soho=db.Column(db.Integer)
    taikei_data=db.Column(db.String(80))
    taikei=db.Column(db.Integer)
    senaka = db.Column(db.Integer)
    do = db.Column(db.Integer)
    siri = db.Column(db.Integer)
    tomo = db.Column(db.Integer)
    harabukuro = db.Column(db.Integer)
    head = db.Column(db.Integer)
    neck = db.Column(db.Integer)
    breast = db.Column(db.Integer)
    shoulder = db.Column(db.Integer)
    zencho = db.Column(db.Integer)
    kocho = db.Column(db.Integer)
    maehaba = db.Column(db.Integer)
    ushirohaba = db.Column(db.Integer)
    maetsunagi = db.Column(db.Integer)
    ushirotsunagi = db.Column(db.Integer)
    tail = db.Column(db.Integer)
    furikata = db.Column(db.Integer)
    taikei_sogo1=db.Column(db.Integer)
    taikei_sogo2=db.Column(db.Integer)
    taikei_sogo3=db.Column(db.Integer)
    umatokki1=db.Column(db.Integer)
    umatokki2=db.Column(db.Integer)
    umatokki3=db.Column(db.Integer)
    horse_start_score=db.Column(db.Integer)
    horse_latestart_rate=db.Column(db.Integer)
    sanko_zenso=db.Column(db.Integer)
    sanko_zenso_jockey_code=db.Column(db.String(80))
    mambaken_score=db.Column(db.Integer)
    mambaken_shirushi=db.Column(db.Integer)
    kokyu_flg=db.Column(db.Integer)
    gekiso_type=db.Column(db.String(80))
    rest_reason_code=db.Column(db.Integer)
    flg=db.Column(db.String(80))
    turf_dart_steeple_flg=db.Column(db.Integer)
    distance_flg=db.Column(db.Integer)
    class_flg=db.Column(db.Integer)
    tenkyu_flg=db.Column(db.Integer)
    kyosei_flg=db.Column(db.Integer)
    norikae_flg=db.Column(db.Integer)
    runtimes_first_train=db.Column(db.Integer)
    date_first_train=db.Column(db.Integer)
    days_after_first_train=db.Column(db.Integer)
    hobokusaki=db.Column(db.String(80))
    hobokusaki_rank=db.Column(db.String(80))
    trainer_rank=db.Column(db.Integer)

class SeisekiData(db.Model):
    __tablename__ = 'seiseki'
    racehorsekey=db.Column(db.String(80),primary_key=True)
    racekey=db.Column(db.String(80))
    bacode=db.Column(db.Integer)
    year=db.Column(db.Integer)
    kai=db.Column(db.Integer)
    day=db.Column(db.Integer)
    raceno=db.Column(db.Integer)
    seisekirace = db.relationship("SeisekiRaceData", uselist=False, backref=db.backref("seiseki"))
    num=db.Column(db.Integer)
    raceseisekikey=db.Column(db.String(80))
    blood=db.Column(db.Integer)
    ymd=db.Column(db.String(80))
    horse=db.Column(db.String(80))
    distance=db.Column(db.Integer)
    tdscode=db.Column(db.Integer)
    right_left=db.Column(db.Integer)
    in_out=db.Column(db.Integer)
    baba=db.Column(db.Integer)
    baba_abst=db.Column(db.Integer)
    baba_detail=db.Column(db.Integer)
    shubetsu=db.Column(db.Integer)
    joken=db.Column(db.String(80))
    kigo=db.Column(db.Integer)
    juryo=db.Column(db.Integer)
    grade=db.Column(db.Integer)
    racename=db.Column(db.String(80))
    num_of_all_horse=db.Column(db.Integer)
    racename_ryaku=db.Column(db.String(80))
    order_of_arrival=db.Column(db.Integer)
    ijo_kbn=db.Column(db.Integer)
    time=db.Column(db.Integer)
    kinryo=db.Column(db.Integer)
    jockey_name=db.Column(db.String(80))
    trainer_name=db.Column(db.String(80))
    decided_odds=db.Column(db.Integer)
    decided_pop_order=db.Column(db.Integer)
    idm=db.Column(db.Integer)
    natural_score=db.Column(db.Integer)
    baba_sa=db.Column(db.Integer)
    pace=db.Column(db.Integer)
    start_late=db.Column(db.Integer)
    position=db.Column(db.Integer)
    furi=db.Column(db.Integer)
    mae_furi=db.Column(db.Integer)
    naka_furi=db.Column(db.Integer)
    ushiro_furi=db.Column(db.Integer)
    race=db.Column(db.Integer)
    course_position=db.Column(db.Integer)
    up_code=db.Column(db.Integer)
    class_code=db.Column(db.Integer)
    batai_code=db.Column(db.Integer)
    kehai_code=db.Column(db.Integer)
    racepace=db.Column(db.String(80))
    umapace=db.Column(db.String(80))
    ten_score=db.Column(db.Integer)
    up_score=db.Column(db.Integer)
    pace_score=db.Column(db.Integer)
    racep_score=db.Column(db.Integer)
    win_horse_name=db.Column(db.String(80))
    time_sa=db.Column(db.Integer)
    mae3f_time=db.Column(db.Integer)
    agari3f_time=db.Column(db.Integer)
    biko=db.Column(db.String(80))
    yobi=db.Column(db.String(80))
    decided_place_odds=db.Column(db.Integer)
    juji_win_odds=db.Column(db.Integer)
    juji_place_odds=db.Column(db.Integer)
    corner_order1=db.Column(db.Integer)
    corner_order2=db.Column(db.Integer)
    corner_order3=db.Column(db.Integer)
    corner_order4=db.Column(db.Integer)
    mae3f_sa=db.Column(db.Integer)
    agari3f_sa=db.Column(db.Integer)
    jockey_code=db.Column(db.Integer)
    trainer_code=db.Column(db.Integer)
    weight=db.Column(db.Integer)
    weight_increase=db.Column(db.Integer)
    tenko=db.Column(db.Integer)
    course=db.Column(db.Integer)
    race_leg_type=db.Column(db.String(80))
    win_ret=db.Column(db.Integer)
    place_ret=db.Column(db.Integer)
    this_money=db.Column(db.Integer)
    earned_money=db.Column(db.Integer)
    race_pace_flow=db.Column(db.Integer)
    horse_pace_flow=db.Column(db.Integer)
    corner4_course_position=db.Column(db.Integer)

class SeisekiRaceData(db.Model):
    __tablename__ = 'seisekirace'
    racekey=db.Column(db.String(80),db.ForeignKey('seiseki.racekey'),primary_key=True)
    furlongtime1=db.Column(db.Integer)
    furlongtime2=db.Column(db.Integer)
    furlongtime3=db.Column(db.Integer)
    furlongtime4=db.Column(db.Integer)
    furlongtime5=db.Column(db.Integer)
    furlongtime6=db.Column(db.Integer)
    furlongtime7=db.Column(db.Integer)
    furlongtime8=db.Column(db.Integer)
    furlongtime9=db.Column(db.Integer)
    furlongtime10=db.Column(db.Integer)
    furlongtime11=db.Column(db.Integer)
    furlongtime12=db.Column(db.Integer)
    furlongtime13=db.Column(db.Integer)
    furlongtime14=db.Column(db.Integer)
    furlongtime15=db.Column(db.Integer)
    furlongtime16=db.Column(db.Integer)
    furlongtime17=db.Column(db.Integer)
    furlongtime18=db.Column(db.Integer)
    corner1=db.Column(db.String(80))
    corner2=db.Column(db.String(80))
    corner3=db.Column(db.String(80))
    corner4=db.Column(db.String(80))
    paceupposition=db.Column(db.Integer)
    truckbias1_in=db.Column(db.String(80))
    truckbias1_center=db.Column(db.String(80))
    truckbias1_out=db.Column(db.String(80))
    truckbias2_in=db.Column(db.String(80))
    truckbias2_center=db.Column(db.String(80))
    truckbias2_out=db.Column(db.String(80))
    truckbias_muko_in=db.Column(db.String(80))
    truckbias_muko_center=db.Column(db.String(80))
    truckbias_muko_out=db.Column(db.String(80))
    truckbias3_in=db.Column(db.String(80))
    truckbias3_center=db.Column(db.String(80))
    truckbias3_out=db.Column(db.String(80))
    truckbias4_saiuchi=db.Column(db.String(80))
    truckbias4_in=db.Column(db.String(80))
    truckbias4_center=db.Column(db.String(80))
    truckbias4_out=db.Column(db.String(80))
    truckbias4_oosoto=db.Column(db.String(80))
    truckbias_straight_saiuchi=db.Column(db.String(80))
    truckbias_straight_in=db.Column(db.String(80))
    truckbias_straight_center=db.Column(db.String(80))
    truckbias_straight_out=db.Column(db.String(80))
    truckbias_straight_oosoto=db.Column(db.String(80))
    comment=db.Column(db.String(80))

class KaisaiData(db.Model):
    __tablename__ = 'kaisai'
    kaisaikey=db.Column(db.String(80),primary_key=True)
    #子に対して
    races = db.relationship('BangumiData',backref=db.backref('kaisai'),lazy='subquery',innerjoin=True)
    ymd=db.Column(db.Integer)
    kaisai_kbn=db.Column(db.Integer)
    day_of_week=db.Column(db.String(80))
    course_name=db.Column(db.String(80))
    tenko=db.Column(db.Integer,db.ForeignKey('tenkomaster.tenko'))
    turf_baba=db.Column(db.Integer)
    turf_baba_abst=db.Column(db.Integer)
    turf_baba_detail=db.Column(db.Integer)
    turf_baba_in=db.Column(db.Integer)
    turf_baba_center=db.Column(db.Integer)
    turf_baba_out=db.Column(db.Integer)
    turf_baba_sa=db.Column(db.Integer)
    turf_baba_straight_saiuchi=db.Column(db.Integer)
    turf_baba_straight_in=db.Column(db.Integer)
    turf_baba_straight_center=db.Column(db.Integer)
    turf_baba_straight_out=db.Column(db.Integer)
    turf_baba_straight_oosoto=db.Column(db.Integer)
    dart_baba=db.Column(db.Integer)
    dart_baba_abst=db.Column(db.Integer)
    dart_baba_detail=db.Column(db.Integer)
    dart_baba_in=db.Column(db.Integer)
    dart_baba_center=db.Column(db.Integer)
    dart_baba_out=db.Column(db.Integer)
    dart_baba_sa=db.Column(db.Integer)
    data_kbn=db.Column(db.Integer)
    renzoku_day=db.Column(db.Integer)
    turf_kind=db.Column(db.Integer)
    turf_length=db.Column(db.Integer)
    tennatsu=db.Column(db.Integer)
    stopfreeze=db.Column(db.Integer)
    precipitation=db.Column(db.Integer)

class TrainAnalysisData(db.Model):
    __tablename__ = 'train_analysis'
    racehorsekey=db.Column(db.String(80),db.ForeignKey('racehorse.racehorsekey'),primary_key=True)
    racekey=db.Column(db.String(80))
    num=db.Column(db.Integer)
    train_type=db.Column(db.String(80))
    train_course_kind=db.Column(db.String(80))
    saka=db.Column(db.Integer)
    wood=db.Column(db.Integer)
    dart=db.Column(db.Integer)
    turf=db.Column(db.Integer)
    pool=db.Column(db.Integer)
    steeple=db.Column(db.Integer)
    politruck=db.Column(db.Integer)
    train_distance=db.Column(db.Integer)
    train_juten=db.Column(db.Integer)
    oikiri_score=db.Column(db.Integer)
    shiage_score=db.Column(db.Integer)
    train_vol_hyoka=db.Column(db.String(80))
    shiage_score_change=db.Column(db.Integer)
    train_comment=db.Column(db.String(80))
    comment_date=db.Column(db.String(80))
    train_hyoka=db.Column(db.Integer)

class TrainOikiriData(db.Model):
    __tablename__ = 'train_oikiri'
    racehorsekey=db.Column(db.String(80),db.ForeignKey('racehorse.racehorsekey'),primary_key=True)
    racekey=db.Column(db.String(80))
    num=db.Column(db.Integer)
    oikiristateidx = db.relationship("OikiriStateIndex",uselist=False,backref=db.backref("train_oikiri"))
    traincoureidx = db.relationship("TrainCourseCodeIndex",uselist=False,backref=db.backref("train_oikri"))
    day_of_week=db.Column(db.String(80))
    train_date=db.Column(db.String(80))
    kaisu=db.Column(db.Integer)
    train_course_code=db.Column(db.String(80))
    oikiri_kind=db.Column(db.Integer)
    oikiri_state=db.Column(db.Integer)
    rider=db.Column(db.Integer)
    train_f=db.Column(db.Integer)
    ten_f=db.Column(db.Integer)
    mid_f=db.Column(db.Integer)
    end_f=db.Column(db.Integer)
    ten_f_score=db.Column(db.Integer)
    mid_f_score=db.Column(db.Integer)
    end_f_score=db.Column(db.Integer)
    oikiri_score=db.Column(db.Integer)
    awase_result=db.Column(db.String(80))
    aite_oikiri_kind=db.Column(db.Integer)
    aite_age=db.Column(db.Integer)
    aite_class=db.Column(db.String(80))

class ReturninfoData(db.Model):
    __tablename__ = 'returninfo'
    racekey=db.Column(db.String(80),db.ForeignKey('bangumi.racekey'),primary_key=True)
    win1_num=db.Column(db.Integer)
    win1_ret=db.Column(db.Integer)
    win2_num=db.Column(db.Integer)
    win2_ret=db.Column(db.Integer)
    win3_num=db.Column(db.Integer)
    win3_ret=db.Column(db.Integer)
    place1_num=db.Column(db.Integer)
    place1_ret=db.Column(db.Integer)
    place2_num=db.Column(db.Integer)
    place2_ret=db.Column(db.Integer)
    place3_num=db.Column(db.Integer)
    place3_ret=db.Column(db.Integer)
    place4_num=db.Column(db.Integer)
    place4_ret=db.Column(db.Integer)
    place5_num=db.Column(db.Integer)
    place5_ret=db.Column(db.Integer)
    wakuren1_num1=db.Column(db.Integer)
    wakuren1_num2=db.Column(db.Integer)
    wakuren1_ret=db.Column(db.Integer)
    wakuren2_num1=db.Column(db.Integer)
    wakuren2_num2=db.Column(db.Integer)
    wakuren2_ret=db.Column(db.Integer)
    wakuren3_num1=db.Column(db.Integer)
    wakuren3_num2=db.Column(db.Integer)
    wakuren3_ret=db.Column(db.Integer)
    umaren1_num1=db.Column(db.Integer)
    umaren1_num2=db.Column(db.Integer)
    umaren1_ret=db.Column(db.Integer)
    umaren2_num1=db.Column(db.Integer)
    umaren2_num2=db.Column(db.Integer)
    umaren2_ret=db.Column(db.Integer)
    umaren3_num1=db.Column(db.Integer)
    umaren3_num2=db.Column(db.Integer)
    umaren3_ret=db.Column(db.Integer)
    wide1_num1=db.Column(db.Integer)
    wide1_num2=db.Column(db.Integer)
    wide1_ret=db.Column(db.Integer)
    wide2_num1=db.Column(db.Integer)
    wide2_num2=db.Column(db.Integer)
    wide2_ret=db.Column(db.Integer)
    wide3_num1=db.Column(db.Integer)
    wide3_num2=db.Column(db.Integer)
    wide3_ret=db.Column(db.Integer)
    wide4_num1=db.Column(db.Integer)
    wide4_num2=db.Column(db.Integer)
    wide4_ret=db.Column(db.Integer)
    wide5_num1=db.Column(db.Integer)
    wide5_num2=db.Column(db.Integer)
    wide5_ret=db.Column(db.Integer)
    wide6_num1=db.Column(db.Integer)
    wide6_num2=db.Column(db.Integer)
    wide6_ret=db.Column(db.Integer)
    wide7_num1=db.Column(db.Integer)
    wide7_num2=db.Column(db.Integer)
    wide7_ret=db.Column(db.Integer)
    umatan1_num1=db.Column(db.Integer)
    umatan1_num2=db.Column(db.Integer)
    umatan1_ret=db.Column(db.Integer)
    umatan2_num1=db.Column(db.Integer)
    umatan2_num2=db.Column(db.Integer)
    umatan2_ret=db.Column(db.Integer)
    umatan3_num1=db.Column(db.Integer)
    umatan3_num2=db.Column(db.Integer)
    umatan3_ret=db.Column(db.Integer)
    umatan4_num1=db.Column(db.Integer)
    umatan4_num2=db.Column(db.Integer)
    umatan4_ret=db.Column(db.Integer)
    umatan5_num1=db.Column(db.Integer)
    umatan5_num2=db.Column(db.Integer)
    umatan5_ret=db.Column(db.Integer)
    umatan6_num1=db.Column(db.Integer)
    umatan6_num2=db.Column(db.Integer)
    umatan6_ret=db.Column(db.Integer)
    sanrenpuku1_num1=db.Column(db.Integer)
    sanrenpuku1_num2=db.Column(db.Integer)
    sanrenpuku1_num3=db.Column(db.Integer)
    sanrenpuku1_ret=db.Column(db.Integer)
    sanrenpuku2_num1=db.Column(db.Integer)
    sanrenpuku2_num2=db.Column(db.Integer)
    sanrenpuku2_num3=db.Column(db.Integer)
    sanrenpuku2_ret=db.Column(db.Integer)
    sanrenpuku3_num1=db.Column(db.Integer)
    sanrenpuku3_num2=db.Column(db.Integer)
    sanrenpuku3_num3=db.Column(db.Integer)
    sanrenpuku3_ret=db.Column(db.Integer)
    sanrentan1_num1=db.Column(db.Integer)
    sanrentan1_num2=db.Column(db.Integer)
    sanrentan1_num3=db.Column(db.Integer)
    sanrentan1_ret=db.Column(db.Integer)
    sanrentan2_num1=db.Column(db.Integer)
    sanrentan2_num2=db.Column(db.Integer)
    sanrentan2_num3=db.Column(db.Integer)
    sanrentan2_ret=db.Column(db.Integer)
    sanrentan3_num1=db.Column(db.Integer)
    sanrentan3_num2=db.Column(db.Integer)
    sanrentan3_num3=db.Column(db.Integer)
    sanrentan3_ret=db.Column(db.Integer)
    sanrentan4_num1=db.Column(db.Integer)
    sanrentan4_num2=db.Column(db.Integer)
    sanrentan4_num3=db.Column(db.Integer)
    sanrentan4_ret=db.Column(db.Integer)
    sanrentan5_num1=db.Column(db.Integer)
    sanrentan5_num2=db.Column(db.Integer)
    sanrentan5_num3=db.Column(db.Integer)
    sanrentan5_ret=db.Column(db.Integer)
    sanrentan6_num1=db.Column(db.Integer)
    sanrentan6_num2=db.Column(db.Integer)
    sanrentan6_num3=db.Column(db.Integer)
    sanrentan6_ret=db.Column(db.Integer)

class BacodeMaster(db.Model):
    __tablename__ = 'bacodemaster'
    bacode = db.Column(db.Integer,primary_key=True)
    baname = db.Column(db.String(80))

class JuryoMaster(db.Model):
    __tablename__ = 'juryomaster'
    juryo = db.Column(db.Integer,primary_key=True)
    juryo_name = db.Column(db.String(80))

class JokenMaster(db.Model):
    __tablename__ = 'jokenmaster'
    joken = db.Column(db.String(80),primary_key=True)
    joken_group = db.Column(db.Integer)
    joken_name = db.Column(db.String(80))

class JokenGroupMaster(db.Model):
    __tablename__ = 'jokengroupmaster'
    joken_group = db.Column(db.Integer,primary_key = True)
    joken_group_name = db.Column(db.String(80))

class ShubetsuMaster(db.Model):
    __tablename__ = 'shubetsumaster'
    shubetsu = db.Column(db.Integer,primary_key = True)
    shubetsu_name = db.Column(db.String(80))
        
class IjokbnMaster(db.Model):
    __tablename__ = 'ijokbnmaster'
    ijo_kbn = db.Column(db.Integer,primary_key = True)
    ijo_kbn_name = db.Column(db.String(80))

class TenkoMaster(db.Model):
    __tablename__ = 'tenkomaster'
    tenko = db.Column(db.Integer,primary_key = True)
    tenko_name = db.Column(db.String(80))    
    kaisai = db.relationship("KaisaiData", uselist=False,backref=db.backref("tenkoma"))

class RestreasoncodeMaster(db.Model):
    __tablename__ = 'restreasoncodemaster'
    rest_reason_code = db.Column(db.Integer,primary_key = True)
    rest_reason_name = db.Column(db.String(80))

class LegtypeMaster(db.Model):
    __tablename__ = 'legtypemaster'
    leg_type = db.Column(db.Integer,primary_key = True)
    race_leg_type = db.Column(db.String(80))
    leg_type_name = db.Column(db.String(80))

class DistanceadjustMaster(db.Model):
    __tablename__ = 'distanceadjustmaster'
    distance_adjust = db.Column(db.Integer,primary_key = True)
    distance_name = db.Column(db.String(80))

class TrainerData(db.Model):
    __tablename__ = 'trainer'
    trainer_code=db.Column(db.Integer,primary_key=True)
    delete_flg=db.Column(db.Integer)
    delete_ymd=db.Column(db.Integer)
    trainer_name=db.Column(db.String(80))
    trainer_kana=db.Column(db.String(80))
    trainer_name_short=db.Column(db.String(80))
    shozoku_code=db.Column(db.Integer)
    shozoku_region=db.Column(db.String(80))
    birthday=db.Column(db.Integer)
    get_licence_year=db.Column(db.Integer)
    trainer_comment=db.Column(db.String(80))
    comment_ymd=db.Column(db.Integer)
    this_leading=db.Column(db.Integer)
    this_seiseki_flat_1st=db.Column(db.Integer)
    this_seiseki_flat_2nd=db.Column(db.Integer)
    this_seiseki_flat_3rd=db.Column(db.Integer)
    this_seiseki_flat_out=db.Column(db.Integer)
    this_seiseki_steeple_1st=db.Column(db.Integer)
    this_seiseki_steeple_2nd=db.Column(db.Integer)
    this_seiseki_steeple_3rd=db.Column(db.Integer)
    this_seiseki_steeple_out=db.Column(db.Integer)
    this_tokubetsu_win=db.Column(db.Integer)
    this_jusho_win=db.Column(db.Integer)
    last_leading=db.Column(db.Integer)
    last_seiseki_flat_1st=db.Column(db.Integer)
    last_seiseki_flat_2nd=db.Column(db.Integer)
    last_seiseki_flat_3rd=db.Column(db.Integer)
    last_seiseki_flat_out=db.Column(db.Integer)
    last_seiseki_steeple_1st=db.Column(db.Integer)
    last_seiseki_steeple_2nd=db.Column(db.Integer)
    last_seiseki_steeple_3rd=db.Column(db.Integer)
    last_seiseki_steeple_out=db.Column(db.Integer)
    last_tokubetsu_win=db.Column(db.Integer)
    last_jusho_win=db.Column(db.Integer)
    total_seiseki_flat_1st=db.Column(db.Integer)
    total_seiseki_flat_2nd=db.Column(db.Integer)
    total_seiseki_flat_3rd=db.Column(db.Integer)
    total_seiseki_flat_out=db.Column(db.Integer)
    total_seiseki_steeple_1st=db.Column(db.Integer)
    total_seiseki_steeple_2nd=db.Column(db.Integer)
    total_seiseki_steeple_3rd=db.Column(db.Integer)
    total_seiseki_steeple_out=db.Column(db.Integer)
    data_ymd=db.Column(db.Integer)
    trainer_index=db.Column(db.Integer)

class JockeyData(db.Model):
    __tablename__ = 'jockey'
    jockey_code=db.Column(db.Integer,primary_key=True)
    delete_flg=db.Column(db.Integer)
    delete_ymd=db.Column(db.Integer)
    jockey_name=db.Column(db.String(80))
    jockey_name_kana=db.Column(db.String(80))
    jockey_name_short=db.Column(db.String(80))
    shozoku_code=db.Column(db.Integer)
    shozoku_region=db.Column(db.String(80))
    birthday=db.Column(db.Integer)
    get_licence_year=db.Column(db.Integer)
    minarai_kbn=db.Column(db.Integer)
    trainer_code=db.Column(db.Integer)
    jockey_comment=db.Column(db.String(80))
    comment_ymd=db.Column(db.Integer)
    this_leading=db.Column(db.Integer)
    this_flat_seiseki_1st=db.Column(db.Integer)
    this_flat_seiseki_2nd=db.Column(db.Integer)
    this_flat_seiseki_3rd=db.Column(db.Integer)
    this_flat_seiseki_out=db.Column(db.Integer)
    this_steeple_seiseki_1st=db.Column(db.Integer)
    this_steeple_seiseki_2nd=db.Column(db.Integer)
    this_steeple_seiseki_3rd=db.Column(db.Integer)
    this_steeple_seiseki_out=db.Column(db.Integer)
    this_tokubetsu_win=db.Column(db.Integer)
    this_jusho_win=db.Column(db.Integer)
    last_leading=db.Column(db.Integer)
    last_flat_seiseki_1st=db.Column(db.Integer)
    last_flat_seiseki_2nd=db.Column(db.Integer)
    last_flat_seiseki_3rd=db.Column(db.Integer)
    last_flat_seiseki_out=db.Column(db.Integer)
    last_steeple_seiseki_1st=db.Column(db.Integer)
    last_steeple_seiseki_2nd=db.Column(db.Integer)
    last_steeple_seiseki_3rd=db.Column(db.Integer)
    last_steeple_seiseki_out=db.Column(db.Integer)
    last_tokubetsu_win=db.Column(db.Integer)
    last_jusho_win=db.Column(db.Integer)
    total_flat_seiseki_1st=db.Column(db.Integer)
    total_flat_seiseki_2nd=db.Column(db.Integer)
    total_flat_seiseki_3rd=db.Column(db.Integer)
    total_flat_seiseki_out=db.Column(db.Integer)
    total_steeple_seiseki_1st=db.Column(db.Integer)
    total_steeple_seiseki_2nd=db.Column(db.Integer)
    total_steeple_seiseki_3rd=db.Column(db.Integer)
    total_steeple_seiseki_out=db.Column(db.Integer)
    data_ymd=db.Column(db.Integer)
    jockey_index=db.Column(db.Integer)

class HorsebaseData(db.Model):
    __tablename__ = 'horsebase'
    blood=db.Column(db.Integer,db.ForeignKey('racehorse.blood'),primary_key=True)
    horse=db.Column(db.String(80))
    sex=db.Column(db.Integer)
    hair=db.Column(db.Integer)
    umakigo=db.Column(db.Integer)
    father=db.Column(db.String(80))
    mother=db.Column(db.String(80))
    mother_father=db.Column(db.String(80))
    birthday=db.Column(db.Integer)
    father_birthyear=db.Column(db.Integer)
    mother_birthyear=db.Column(db.Integer)
    mother_father_birthyear=db.Column(db.Integer)
    owner=db.Column(db.String(80))
    owner_kai_code=db.Column(db.Integer)
    producer=db.Column(db.String(80))
    locality=db.Column(db.String(80))
    delete_flg=db.Column(db.Integer)
    data_ymd=db.Column(db.Integer)
    father_phylogeny=db.Column(db.Integer)
    mother_phylogeny=db.Column(db.Integer)
    horse_index=db.Column(db.Integer)

class HorseIndex(db.Model):
    __tablename__ = 'horseindex'
    blood = db.Column(db.Integer,db.ForeignKey('racehorse.blood'),primary_key = True)
    index = db.Column(db.Integer)

class JockeyIndex(db.Model):
    __tablename__ = 'jockeyindex'
    jockey_code = db.Column(db.Integer,db.ForeignKey('racehorse.jockey_code'),primary_key = True)
    index = db.Column(db.Integer)

class TrainerIndex(db.Model):
    __tablename__ = 'trainerindex'
    trainer_code = db.Column(db.Integer,db.ForeignKey('racehorse.trainer_code'),primary_key = True)
    index = db.Column(db.Integer)

class OikiriStateIndex(db.Model):
    __tablename__ = 'oikiristateindex'
    oikiri_state = db.Column(db.Integer,db.ForeignKey('train_oikiri.oikiri_state'),primary_key = True)
    index = db.Column(db.Integer)

class TrainCourseCodeIndex(db.Model):
    __tablename__ = 'traincoursecodeindex'
    train_course_code = db.Column(db.String(80),db.ForeignKey('train_oikiri.train_course_code'),primary_key = True)
    index = db.Column(db.Integer)

class HobokusakiIndex(db.Model):
    __tablename__ = 'hobokusakiindex'
    index = db.Column(db.Integer,primary_key = True)
    hobokusaki = db.Column(db.String(80),db.ForeignKey('racehorse.hobokusaki'))
    
class HidumeCodeIndex(db.Model):
    __tablename__ = 'hidumecodeindex'
    hidume_code = db.Column(db.Integer,db.ForeignKey('racehorse.hidume_code'),primary_key = True)
    index = db.Column(db.Integer)

